### ISSUE TITLE
Salesforce connector issue in ESB 5.0 in tenant mode

### ISSUE THREAD

**Issue by kesavany** [wso2-extensions/esb-connector-salesforce#15]
Getting the following error in the tenant mode.

2017-05-25 19:59:04,211] ERROR - PassThroughHttpSender Failed to submit the response
org.apache.axis2.AxisFault: Trying to write END_DOCUMENT when document has no root (ie. trying to output empty document).
at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:78)

**Comment by kesavany** [comment]
Fixed in https://github.com/wso2-extensions/esb-connector-salesforce/pull/14/commits/e38bebf4bd6849712a2db6f3f5b66c366ef34f63
